### ISSUE TITLE
How to use it as the CUDA code for using in PyTorch

### ISSUE THREAD

**Issue by LiWentomng** [Wild-Soul/overlapping-polygon#2]
Thanks your code! I want to use it as the CUDA code for using in PyTorch. Can you provide the CUDA code or explain how to implement this goal? Need your help, thanks!

**Comment by 0x1DKFA** [comment]
Hi I'm not sure about CUDA implementation myself.
I've listed the algorithms that might be useful for you:
* Sutherland Hodgman  (polygon clipping algorithm) -> https://en.wikipedia.org/wiki/Sutherland%E2%80%93Hodgman_algorithm
* For sorting the points in anti-clockwise direction you can either use Maths (will miss some edge cases) or you can go with Graham Scan (https://en.wikipedia.org/wiki/Graham_scan).

In order to get the overlapping area of polygon :
* Using the above two you can get the points of overlapping polygon in anticlockwise order (or clockwise depends upon implementation). Now you can get the overlapping area.

Hope this helps you out.

**Comment by LiWentomng** [comment]
Thank you for sharing！
